# Generated by Django 5.2.7 on 2025-11-04 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '003_fix_favorite_recipes_relationship'),
    ]

    operations = [
        # Thêm cột id vào bảng favorite_recipes trong database
        # Vì managed = False, chúng ta phải sử dụng SQL trực tiếp
        # Bước 1: Thêm cột id (không phải primary key ngay lập tức)
        migrations.RunSQL(
            "ALTER TABLE favorite_recipes ADD COLUMN new_id SERIAL;",
            reverse_sql="ALTER TABLE favorite_recipes DROP COLUMN new_id;"
        ),
        # Bước 2: Cập nhật bảng để có giá trị id cho các bản ghi hiện tại
        migrations.RunSQL(
            "UPDATE favorite_recipes SET new_id = DEFAULT;",
            reverse_sql="UPDATE favorite_recipes SET new_id = NULL;"
        ),
        # Bước 3: Xóa ràng buộc primary key cũ và tạo ràng buộc unique thay thế
        migrations.RunSQL(
            "ALTER TABLE favorite_recipes DROP CONSTRAINT favorite_recipes_pkey;",
            reverse_sql="ALTER TABLE favorite_recipes ADD CONSTRAINT favorite_recipes_pkey PRIMARY KEY (user_id, recipe_id);"
        ),
        # Bước 4: Thêm ràng buộc unique cho (user_id, recipe_id) để duy trì tính duy nhất
        migrations.RunSQL(
            "ALTER TABLE favorite_recipes ADD CONSTRAINT favorite_recipes_user_recipe_unique UNIQUE (user_id, recipe_id);",
            reverse_sql="ALTER TABLE favorite_recipes DROP CONSTRAINT favorite_recipes_user_recipe_unique;"
        ),
        # Bước 5: Thêm ràng buộc primary key cho cột mới
        migrations.RunSQL(
            "ALTER TABLE favorite_recipes ADD CONSTRAINT favorite_recipes_pkey PRIMARY KEY (new_id);",
            reverse_sql="ALTER TABLE favorite_recipes DROP CONSTRAINT favorite_recipes_pkey;"
        ),
        # Bước 6: Đổi tên cột
        migrations.RunSQL(
            "ALTER TABLE favorite_recipes RENAME COLUMN new_id TO id;",
            reverse_sql="ALTER TABLE favorite_recipes RENAME COLUMN id TO new_id;"
        ),
    ]
