# Generated by Django 5.2.7 on 2025-11-04 14:00
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_authgroup_delete_authgrouppermissions_and_more'),
    ]

    operations = [
        # Thay đổi mối quan hệ từ OneToOneField sang ForeignKey cho trường user
        migrations.AlterField(
            model_name='favoriterecipes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='auth.user'),
        ),
    ]
